### ISSUE TITLE
Is it possible to record simultaneously from the rear and front cameras?

### ISSUE THREAD

**Issue by IHIierO** [enebin/Aespa#38]
I want to create an application that records video from two cameras simultaneously and then saves it. I tried to do this by creating two VideoContentViewModels, but it just replaces one session with another.
Also, I cannot place two previews on top of each other because they do not resize.

**Comment by enebin** [comment]
> I want to create an application that records video from two cameras simultaneously and then saves it. I tried to do this by creating two VideoContentViewModels, but it just replaces one session with another.

Using both camera is simultaneously is not supported. For this, it needs to use a new method([AVCaptureMultiCamSession](https://developer.apple.com/documentation/avfoundation/avcapturemulticamsession)), not the existing one, but it's not supported yet.

> Also, I cannot place two previews on top of each other because they do not resize.

I'm not sure that I understood exactly, but if your question pertains to using the two sessions mentioned above simultaneously, it is indeed an action that cannot be done because you cannot create two previews at the same time.

I hope it helps 😄
